name:                typograffiti
version:             0.1.0.0
github:              "schell/typograffiti"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "schell@takt.com"
copyright:           "2018 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Display TTF fonts in OpenGL. Includes caching for fast
                     rendering.
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A library that lets you draw nice text already!

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- freetype2
- gl
- linear
- mtl
- pretty-show
- stm
- template-haskell
- vector

library:
  source-dirs: src

executables:
  typograffiti-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath
    - pretty-show
    - sdl2
    - typograffiti


tests:
  typograffiti-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typograffiti
