name:                typograffiti
version:             0.1.0.0
github:              "githubuser/typograffiti"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/typograffiti#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- freetype2
- gl
- linear
- mtl
- template-haskell
- vector

library:
  source-dirs: src

executables:
  typograffiti-exe:
    main:                Main.hs
    source-dirs:         app
    other-modules:       Paths_typograffiti
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath
    - JuicyPixels
    - sdl2
    - typograffiti


tests:
  typograffiti-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typograffiti
